### ISSUE TITLE
ADHER_INTCARE_SP: failed to parse

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#112]
End user reports that [ADHER_INTCARE_SP](http://bioportal.bioontology.org/ontologies/ADHER_INTCARE_SP) ontology shows "Uploaded, Error Rdf Labels" status in BioPortal. Submission 5 parsing log files contains the following stack trace:

```
E, [2019-04-27T10:44:03.310277 #2180] ERROR -- : ["Exception: Rapper cannot parse turtle file at /tmp/data_triple_store20190427-2180-ny3om3: rapper: Parsing URI file:///tmp/data_triple_store20190427-2180-ny3om3 with parser turtle
rapper: Serializing with serializer ntriples
rapper: Error - URI file:///tmp/data_triple_store20190427-2180-ny3om3:5 - syntax error at '<'
rapper: Parsing returned 4 triples

/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/goo-0bc8c933f3f8/lib/goo/sparql/client.rb:60:in `bnodes_filter_file'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/goo-0bc8c933f3f8/lib/goo/sparql/client.rb:81:in `append_triples_no_bnodes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/goo-0bc8c933f3f8/lib/goo/sparql/client.rb:122:in `append_data_triples'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/goo-0bc8c933f3f8/lib/goo/sparql/client.rb:148:in `append_triples'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:632:in `generate_missing_labels_pre'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:550:in `call'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:550:in `block (2 levels) in loop_classes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:504:in `block in process_callbacks'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:500:in `delete_if'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:500:in `process_callbacks'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:549:in `block in loop_classes'
	/usr/local/rbenv/versions/2.5.3/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:531:in `loop_classes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:1002:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:177:in `process_submission'
```

rapper utility reports no triples errors:

```
[ncbo-deployer@ncbo-prd-app-31 5]$ rapper -i rdfxml -o ntriples owlapi.xrdf > data.triples
rapper: Parsing URI file:///srv/ncbo/share/env/production/repository/ADHER_INTCARE_SP/5/owlapi.xrdf with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Parsing returned 2377 triples
[ncbo-deployer@ncbo-prd-app-31 5]$ rapper -i ntriples -c data.triples
rapper: Parsing URI file:///srv/ncbo/share/env/production/repository/ADHER_INTCARE_SP/5/data.triples with parser ntriples
rapper: Parsing returned 2377 triples
```

**Comment by jvendetti** [comment]
Not reproducible in our staging environment.

**Comment by jvendetti** [comment]
@mdorf - I think we should try re-parsing in production after Alex finishes the UMLS import. The ontology parsed fine in staging: http://stage.bioontology.org/ontologies/ADHER_INTCARE_SP?p=summary.

**Comment by mdorf** [comment]
re-parsed successfully
