### ISSUE TITLE
NCIT: submission 86 failed to finish processing

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#143]
End user reports that the CSV file for the latest submission of NCIT isn't accessible. REST API is returning a 500 error:

```
"Cannot read latest submission upload file: /srv/ncbo/repository/NCIT/86/NCIT.csv.gz"
```

The CSV generation is interleaved with indexing. According to the production log file, the processing errors out during indexing on page 113 of 155:

```
E, [2019-12-30T18:42:44.122453 #28913] ERROR -- : ["Thread 1: ArgumentError: Resource.map_attributes only works for :unmapped instances after retrying 10 times...
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/goo-c384156e6e18/lib/goo/base/resource.rb:234:in `map_attributes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/models/ontology_submission.rb:1235:in `rescue in block (4 levels) in index'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/models/ontology_submission.rb:1221:in `block (4 levels) in index'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/models/ontology_submission.rb:1220:in `each'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/models/ontology_submission.rb:1220:in `block (3 levels) in index'"]

E, [2019-12-30T18:42:44.124804 #28913] ERROR -- : ["Goo::Base::AttributeNotLoaded: Attribute `prefLabel` is not loaded for http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C130736. Loaded attributes: #<Set: {:submission}>.
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/goo-c384156e6e18/lib/goo/base/settings/settings.rb:272:in `block in shape_attribute'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/utils/ontology_csv_writer.rb:41:in `write_class'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/models/ontology_submission.rb:1251:in `block (5 levels) in index'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/models/ontology_submission.rb:88:in `synchronize'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/models/ontology_submission.rb:88:in `synchronize'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/models/ontology_submission.rb:1250:in `block (4 levels) in index'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/models/ontology_submission.rb:1220:in `each'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-ab2c968fafef/lib/ontologies_linked_data/models/ontology_submission.rb:1220:in `block (3 levels) in index'"]
```

... hence no CSV file for download.

**Comment by jvendetti** [comment]
Reprocessed NCIT in production using the `ncbo_ontology_process` script. Passed all phases except for the annotator piece, with the following exception:

```
E, [2020-01-09T13:37:04.602450 #21775] ERROR -- : ["No such file or directory @ rb_sysopen - /srv/ncbo/repository/86/parsing.log
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/gems/logger-1.4.2/lib/logger/log_device.rb:103:in `initialize'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/gems/logger-1.4.2/lib/logger/log_device.rb:103:in `open'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/gems/logger-1.4.2/lib/logger/log_device.rb:103:in `create_logfile'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/gems/logger-1.4.2/lib/logger/log_device.rb:97:in `rescue in open_logfile'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/gems/logger-1.4.2/lib/logger/log_device.rb:93:in `open_logfile'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/gems/logger-1.4.2/lib/logger/log_device.rb:86:in `set_dev'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/gems/logger-1.4.2/lib/logger/log_device.rb:18:in `initialize'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/gems/logger-1.4.2/lib/logger.rb:389:in `new'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/gems/logger-1.4.2/lib/logger.rb:389:in `initialize'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ncbo_annotator-38d7bf735641/lib/ncbo_annotator.rb:238:in `new'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ncbo_annotator-38d7bf735641/lib/ncbo_annotator.rb:238:in `create_term_cache_for_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:221:in `process_annotator'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:182:in `process_submission'
	bin/ncbo_ontology_process:98:in `block in <main>'
	bin/ncbo_ontology_process:81:in `each'
	bin/ncbo_ontology_process:81:in `<main>'"]
```

I manually executed the `ncbo_ontology_annotate_generate_cache` script, which succeeded on the first try.

Processing is now complete and the CSV file is accessible again.
