### ISSUE TITLE
latest_submission call diagnostics and change ideas

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#153]
(1) Is it possible that the latest submission call is contributing to the problem by its fail behaviors? Right now if the call fails it immediately retries, up to 10 times. If that doesn't work it reports a second error. Then we see it retrying again right away, as if the main thread calling it has done a retry.   This could cause hundreds of retries in a very short period.

(2) The latest_submission call response times are a bit odd. 10 seconds is very long for this call; in other places it's a very short call. What would be special about include_status=ready?

> 13:09
> john_graybeal @Alex Skrenchuk what is the last number in the log entries, it looks like an execution time?
If the call includes include_status=ready the calls that return status 200 take 10 seconds; if the return status is 404 the call takes 5 milliseconds; and if it's a regular include=all with return status 200, it takes .0034.
> `172.20.222.51 - ncbobioportal [23/Jan/2020:03:42:59 -0800] "GET /ontologies/SYMP/latest_submission?include=all&include_status=ready HTTP/1.0" 200 2 10.0244`
> `172.20.222.51 - ncbobioportal [23/Jan/2020:03:27:37 -0800] "GET /ontologies/DCM/latest_submission?include=all HTTP/1.0" 200 4956 0.0034`
> 13:10
> I suspect the 'latest_submission throughput' is not distinguishing between the types of calls, nor the return status, so it may not be very meaningful.

(3) There is a pattern in the successful and unsuccessful calls. 
> 13:36 I can see a pattern in the queries before and after the duplicate queries: a query comes every 2-3 seconds on average, but 1 in every 6 to 20 queries gives a 404.

**Comment by graybeal** [comment]
Ideas for changing latest_submission call:

1) Change retries to 5 or 3
2) Change time between each return to something  successively longer 
    - This isn't a good idea because the user experience will be poor, waiting for the retry.
3) Change timeout for the call (can we report whether the GOO call timed out, or just returned bad values)?
4) Increase (or decrease) cache time to try to minimize calls
5) Cache the calls using the cron mechanism we already have in place.
6) Move the retry code up a level.

Need to figure out all places it's being called from. (See #148).

**Comment by graybeal** [comment]
In discussion Misha, Jennifer, and John thought the first thing to try (once we start trying things) is reducing the number of retries.

**Comment by alexskr** [comment]
it looks like latest_submission call never gets cached for ontologies that do not have submissions and in some cases, UI keeps on making exessive number of call to the backend:

`172.20.222.51 - ncbobioportal [28/Jan/2020:21:25:46 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0079
172.20.222.51 - ncbobioportal [28/Jan/2020:21:26:19 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0081
172.20.222.51 - ncbobioportal [28/Jan/2020:21:26:29 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0080
172.20.222.51 - ncbobioportal [28/Jan/2020:21:29:47 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0079
172.20.222.51 - ncbobioportal [28/Jan/2020:21:32:08 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0083
172.20.222.51 - ncbobioportal [28/Jan/2020:21:32:54 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0086
172.20.222.51 - ncbobioportal [28/Jan/2020:21:33:54 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0076
172.20.222.51 - ncbobioportal [28/Jan/2020:21:38:58 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0075
172.20.222.51 - ncbobioportal [28/Jan/2020:21:41:21 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0087
172.20.222.51 - ncbobioportal [28/Jan/2020:21:42:18 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0113
172.20.222.51 - ncbobioportal [28/Jan/2020:21:42:57 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0089
172.20.222.51 - ncbobioportal [28/Jan/2020:21:43:55 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0075
172.20.222.51 - ncbobioportal [28/Jan/2020:21:47:44 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0082
172.20.222.51 - ncbobioportal [28/Jan/2020:21:48:36 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0072
172.20.222.51 - ncbobioportal [28/Jan/2020:21:49:09 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0077
172.20.222.51 - ncbobioportal [28/Jan/2020:21:49:42 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0078
172.20.222.51 - ncbobioportal [28/Jan/2020:21:52:13 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0083
172.20.222.51 - ncbobioportal [28/Jan/2020:21:52:30 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0108
172.20.222.51 - ncbobioportal [28/Jan/2020:21:53:09 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0129
172.20.222.51 - ncbobioportal [28/Jan/2020:21:54:08 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0079
172.20.222.51 - ncbobioportal [28/Jan/2020:21:54:31 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0077
172.20.222.51 - ncbobioportal [28/Jan/2020:21:55:34 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0071
172.20.222.51 - ncbobioportal [28/Jan/2020:21:56:10 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0087
172.20.222.51 - ncbobioportal [28/Jan/2020:21:56:20 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0092
172.20.222.51 - ncbobioportal [28/Jan/2020:21:57:11 -0800] "GET /ontologies/FEDORA/latest_submission?include=all HTTP/1.0" 200 2 0.0077`

and we have 3.3K+ hits on just one API server  today for FEDORA ontology latest_submission while there are only a couple of dozen or so external hits for FEDORA ontology on the UI side (reading apache logs)  


NCIT for example gets cached (304) :
`172.20.222.51 - ncbobioportal [28/Jan/2020:10:08:47 -0800] "GET /ontologies/NCIT/latest_submission?include=all HTTP/1.0" 304 - 0.0346
172.20.222.51 - ncbobioportal [28/Jan/2020:10:08:50 -0800] "GET /ontologies/NCIT/latest_submission?include=all HTTP/1.0" 200 5452 0.0037
172.20.222.51 - ncbobioportal [28/Jan/2020:11:09:57 -0800] "GET /ontologies/NCIT/latest_submission?include=all HTTP/1.0" 304 - 0.0384
172.20.222.51 - ncbobioportal [28/Jan/2020:13:00:45 -0800] "GET /ontologies/NCIT/latest_submission?include=all HTTP/1.0" 200 5452 0.0037
172.20.222.51 - ncbobioportal [28/Jan/2020:13:05:24 -0800] "GET /ontologies/NCIT/latest_submission?include=all HTTP/1.0" 200 5452 0.3000`

**Comment by alexskr** [comment]
although this excessive number of calls could also happen for normal ontologies:
`172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0040
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0039
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0047
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0042
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0039
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0037
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0036
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0037
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0042
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0042
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0038
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0045
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0045
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0039
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0042
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0038
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0037
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0037
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:11 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0037
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0045
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0039
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0038
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0038
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0038
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0039
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0041
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0045
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0038
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0039
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0040
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0038
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0039
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0038
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0038
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0039
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0041
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0038
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0040
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0040
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0042
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0039
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0043
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0043
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0046
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0043
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0043
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0043
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0042
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0041
172.20.222.51 - ncbobioportal [28/Jan/2020:12:57:12 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 304 - 0.0040
172.20.222.51 - ncbobioportal [28/Jan/2020:13:05:03 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 200 4965 0.1127
172.20.222.51 - ncbobioportal [28/Jan/2020:13:25:40 -0800] "GET /ontologies/CPT/latest_submission?include=all HTTP/1.0" 200 4965 0.1284
172.20.222.51 - ncbobioportal [28/Jan/2020:14:52:46 -0800] "GET /ontologies/CPT/latest_submission?include=all HT`

but it doesn't go on forever like the FEDORA;  UI issues a couple of dozens calls for two seconds and moves on.

**Comment by alexskr** [comment]
UI throws a 500 errors for ajax calls when I visit FEDORA ontology summary page.  Oddly enough the 500 error is not really visible without turning on developer mode on the browser. 

`I, [2020-01-28T22:50:10.109367 #24994]  INFO -- : Started GET "/ontologies/FEDORA" for 171.66.184.249 at 2020-01-28 22:50:10 -0800
I, [2020-01-28T22:50:10.110551 #24994]  INFO -- : Processing by OntologiesController#show as HTML
I, [2020-01-28T22:50:10.110609 #24994]  INFO -- :   Parameters: {"id"=>"FEDORA"}
E, [2020-01-28T22:50:10.400156 #24994] ERROR -- : No submissions for ontology: http://data.bioontology.org/ontologies/FEDORA
I, [2020-01-28T22:50:10.636538 #24994]  INFO -- :   Rendered ontologies/_submissions.html.haml (16.3ms)
I, [2020-01-28T22:50:10.638255 #24994]  INFO -- :   Rendered ontologies/_visits.html.haml (0.2ms)
I, [2020-01-28T22:50:10.640865 #24994]  INFO -- :   Rendered layouts/_topnav.html.haml (0.9ms)
I, [2020-01-28T22:50:10.641127 #24994]  INFO -- :   Rendered layouts/_notices.html.erb (0.1ms)
I, [2020-01-28T22:50:10.641211 #24994]  INFO -- :   Rendered layouts/_header.html.erb (2.5ms)
I, [2020-01-28T22:50:10.643516 #24994]  INFO -- :   Rendered application/_ga_tracking.html.haml (0.1ms)
I, [2020-01-28T22:50:10.643606 #24994]  INFO -- :   Rendered layouts/_footer.html.haml (1.1ms)
I, [2020-01-28T22:50:10.643682 #24994]  INFO -- :   Rendered ontologies/_metadata.html.haml (28.3ms)
I, [2020-01-28T22:50:10.643926 #24994]  INFO -- : Completed 200 OK in 533ms (Views: 28.8ms)
I, [2020-01-28T22:50:11.454066 #24994]  INFO -- : Started GET "/ajax/classes/treeview?ontology=FEDORA&conceptid=root" for 171.66.184.249 at 2020-01-28 22:50:11 -0800
I, [2020-01-28T22:50:11.455011 #24994]  INFO -- : Processing by ConceptsController#show_tree as */*
I, [2020-01-28T22:50:11.455071 #24994]  INFO -- :   Parameters: {"ontology"=>"FEDORA", "conceptid"=>"root"}
I, [2020-01-28T22:50:11.674672 #24994]  INFO -- : Completed 500 Internal Server Error in 219ms
F, [2020-01-28T22:50:11.675400 #24994] FATAL -- :
F, [2020-01-28T22:50:11.675471 #24994] FATAL -- : NoMethodError (undefined method `first' for nil:NilClass):
F, [2020-01-28T22:50:11.675501 #24994] FATAL -- :
F, [2020-01-28T22:50:11.675534 #24994] FATAL -- : app/controllers/application_controller.rb:402:in `get_class'
app/controllers/concepts_controller.rb:82:in `show_tree'
I, [2020-01-28T22:50:11.676078 #24994]  INFO -- : Processing by ErrorsController#internal_server_error as */*
I, [2020-01-28T22:50:11.676137 #24994]  INFO -- :   Parameters: {"ontology"=>"FEDORA", "conceptid"=>"root"}
I, [2020-01-28T22:50:11.680364 #24994]  INFO -- :   Rendering errors/internal_server_error.html.erb within layouts/ontology
I, [2020-01-28T22:50:11.681066 #24994]  INFO -- :   Rendered errors/internal_server_error.html.erb within layouts/ontology (0.6ms)
I, [2020-01-28T22:50:11.683282 #24994]  INFO -- :   Rendered layouts/_topnav.html.haml (1.1ms)
I, [2020-01-28T22:50:11.683586 #24994]  INFO -- :   Rendered layouts/_notices.html.erb (0.1ms)
I, [2020-01-28T22:50:11.683669 #24994]  INFO -- :   Rendered layouts/_header.html.erb (2.3ms)
I, [2020-01-28T22:50:11.684942 #24994]  INFO -- :   Rendered application/_ga_tracking.html.haml (0.1ms)
I, [2020-01-28T22:50:11.685040 #24994]  INFO -- :   Rendered layouts/_footer.html.haml (1.2ms)
I, [2020-01-28T22:50:11.685295 #24994]  INFO -- : Completed 500 Internal Server Error in 9ms (Views: 7.9ms)
I, [2020-01-28T22:50:11.688184 #24994]  INFO -- : Started GET "/ontologies/FEDORA?p=classes&ajax=true" for 171.66.184.249 at 2020-01-28 22:50:11 -0800
I, [2020-01-28T22:50:11.689246 #24994]  INFO -- : Processing by OntologiesController#show as HTML
I, [2020-01-28T22:50:11.689331 #24994]  INFO -- :   Parameters: {"p"=>"classes", "ajax"=>"true", "id"=>"FEDORA"}
E, [2020-01-28T22:50:12.115286 #24994] ERROR -- : No submissions for ontology: http://data.bioontology.org/ontologies/FEDORA
I, [2020-01-28T22:50:12.146949 #24994]  INFO -- : Completed 500 Internal Server Error in 457ms
F, [2020-01-28T22:50:12.147773 #24994] FATAL -- :
F, [2020-01-28T22:50:12.147834 #24994] FATAL -- : NoMethodError (undefined method `first' for nil:NilClass):
F, [2020-01-28T22:50:12.147863 #24994] FATAL -- :
F, [2020-01-28T22:50:12.147888 #24994] FATAL -- : app/controllers/application_controller.rb:402:in `get_class'
app/controllers/ontologies_controller.rb:139:in `classes'
app/controllers/ontologies_controller.rb:303:in `show'
I, [2020-01-28T22:50:12.148489 #24994]  INFO -- : Processing by ErrorsController#internal_server_error as HTML
I, [2020-01-28T22:50:12.148546 #24994]  INFO -- :   Parameters: {"p"=>"classes", "ajax"=>"true", "id"=>"FEDORA"}
I, [2020-01-28T22:50:12.150034 #24994]  INFO -- :   Rendering errors/internal_server_error.html.erb within layouts/ontology
I, [2020-01-28T22:50:12.150302 #24994]  INFO -- :   Rendered errors/internal_server_error.html.erb within layouts/ontology (0.2ms)
I, [2020-01-28T22:50:12.152710 #24994]  INFO -- :   Rendered layouts/_topnav.html.haml (1.2ms)
I, [2020-01-28T22:50:12.152986 #24994]  INFO -- :   Rendered layouts/_notices.html.erb (0.1ms)
I, [2020-01-28T22:50:12.153133 #24994]  INFO -- :   Rendered layouts/_header.html.erb (2.5ms)
I, [2020-01-28T22:50:12.154488 #24994]  INFO -- :   Rendered application/_ga_tracking.html.haml (0.1ms)
I, [2020-01-28T22:50:12.154647 #24994]  INFO -- :   Rendered layouts/_footer.html.haml (1.3ms)
I, [2020-01-28T22:50:12.154895 #24994]  INFO -- : Completed 500 Internal Server Error in 6ms (Views: 5.1ms)
I, [2020-01-28T22:50:12.157542 #24994]  INFO -- : Started GET "/ontologies/FEDORA?p=properties&ajax=true" for 171.66.184.249 at 2020-01-28 22:50:12 -0800
I, [2020-01-28T22:50:12.158474 #24994]  INFO -- : Processing by OntologiesController#show as HTML
I, [2020-01-28T22:50:12.158530 #24994]  INFO -- :   Parameters: {"p"=>"properties", "ajax"=>"true", "id"=>"FEDORA"}
E, [2020-01-28T22:50:12.479044 #24994] ERROR -- : No submissions for ontology: http://data.bioontology.org/ontologies/FEDORA
I, [2020-01-28T22:50:12.493325 #24994]  INFO -- :   Rendering ontologies/properties.html.haml
I, [2020-01-28T22:50:12.493621 #24994]  INFO -- :   Rendered ontologies/properties.html.haml (0.2ms)
I, [2020-01-28T22:50:12.493873 #24994]  INFO -- : Completed 200 OK in 335ms (Views: 0.7ms)
I, [2020-01-28T22:50:12.497218 #24994]  INFO -- : Started GET "/ontologies/FEDORA?p=mappings&ajax=true" for 171.66.184.249 at 2020-01-28 22:50:12 -0800
I, [2020-01-28T22:50:12.498056 #24994]  INFO -- : Processing by OntologiesController#show as HTML
I, [2020-01-28T22:50:12.498119 #24994]  INFO -- :   Parameters: {"p"=>"mappings", "ajax"=>"true", "id"=>"FEDORA"}
E, [2020-01-28T22:50:12.766890 #24994] ERROR -- : No submissions for ontology: http://data.bioontology.org/ontologies/FEDORA
I, [2020-01-28T22:50:12.830613 #24994]  INFO -- :   Rendered mappings/_count.html.haml (3.3ms)
I, [2020-01-28T22:50:12.830742 #24994]  INFO -- :   Rendered ontologies/_mappings.html.haml (7.6ms)
I, [2020-01-28T22:50:12.830989 #24994]  INFO -- : Completed 200 OK in 333ms (Views: 10.7ms)
I, [2020-01-28T22:50:12.834086 #24994]  INFO -- : Started GET "/ontologies/FEDORA?p=notes&ajax=true" for 171.66.184.249 at 2020-01-28 22:50:12 -0800
I, [2020-01-28T22:50:12.834892 #24994]  INFO -- : Processing by OntologiesController#show as HTML
I, [2020-01-28T22:50:12.834943 #24994]  INFO -- :   Parameters: {"p"=>"notes", "ajax"=>"true", "id"=>"FEDORA"}
E, [2020-01-28T22:50:13.045861 #24994] ERROR -- : No submissions for ontology: http://data.bioontology.org/ontologies/FEDORA
I, [2020-01-28T22:50:13.183193 #24994]  INFO -- :   Rendered notes/_ontology_list.html.haml (1.1ms)
I, [2020-01-28T22:50:13.183315 #24994]  INFO -- :   Rendered ontologies/_notes.html.erb (1.4ms)
I, [2020-01-28T22:50:13.183562 #24994]  INFO -- : Completed 200 OK in 348ms (Views: 1.8ms)
I, [2020-01-28T22:50:13.186568 #24994]  INFO -- : Started GET "/ontologies/FEDORA?p=widgets&ajax=true" for 171.66.184.249 at 2020-01-28 22:50:13 -0800
I, [2020-01-28T22:50:13.187399 #24994]  INFO -- : Processing by OntologiesController#show as HTML
I, [2020-01-28T22:50:13.187470 #24994]  INFO -- :   Parameters: {"p"=>"widgets", "ajax"=>"true", "id"=>"FEDORA"}
E, [2020-01-28T22:50:13.402275 #24994] ERROR -- : No submissions for ontology: http://data.bioontology.org/ontologies/FEDORA
I, [2020-01-28T22:50:13.447510 #24994]  INFO -- :   Rendered ontologies/_widgets.html.haml (29.0ms)
I, [2020-01-28T22:50:13.447777 #24994]  INFO -- : Completed 500 Internal Server Error in 260ms
F, [2020-01-28T22:50:13.448634 #24994] FATAL -- :
F, [2020-01-28T22:50:13.448687 #24994] FATAL -- : ActionView::Template::Error (undefined method `first' for nil:NilClass):
F, [2020-01-28T22:50:13.448855 #24994] FATAL -- :     134:                           %code uri
    135:                           put the complete URI of the class (e.g.,
    136:                           = succeed ")" do
    137:                             %a.external.free{:href => @ontology.explore.classes["collection"].first.id, :rel => "nofollow", :title => "/visualize/39478/Common_Neoplasm"}
    138:                               = @ontology.explore.classes["collection"].first.id
    139:                         %li
    140:                           %code shortid
F, [2020-01-28T22:50:13.448895 #24994] FATAL -- :
F, [2020-01-28T22:50:13.448926 #24994] FATAL -- : app/views/ontologies/_widgets.html.haml:137:in `block in _app_views_ontologies__widgets_html_haml__2116238707275789276_70062589344920'
app/views/ontologies/_widgets.html.haml:136:in `_app_views_ontologies__widgets_html_haml__2116238707275789276_70062589344920'
app/controllers/ontologies_controller.rb:389:in `widgets'
app/controllers/ontologies_controller.rb:312:in `show'
I, [2020-01-28T22:50:13.449508 #24994]  INFO -- : Processing by ErrorsController#internal_server_error as HTML
I, [2020-01-28T22:50:13.449563 #24994]  INFO -- :   Parameters: {"p"=>"widgets", "ajax"=>"true", "id"=>"FEDORA"}
I, [2020-01-28T22:50:13.450928 #24994]  INFO -- :   Rendering errors/internal_server_error.html.erb within layouts/ontology
I, [2020-01-28T22:50:13.451202 #24994]  INFO -- :   Rendered errors/internal_server_error.html.erb within layouts/ontology (0.2ms)
I, [2020-01-28T22:50:13.453224 #24994]  INFO -- :   Rendered layouts/_topnav.html.haml (1.0ms)
I, [2020-01-28T22:50:13.453513 #24994]  INFO -- :   Rendered layouts/_notices.html.erb (0.1ms)
I, [2020-01-28T22:50:13.453598 #24994]  INFO -- :   Rendered layouts/_header.html.erb (2.1ms)
I, [2020-01-28T22:50:13.454759 #24994]  INFO -- :   Rendered application/_ga_tracking.html.haml (0.1ms)
I, [2020-01-28T22:50:13.454849 #24994]  INFO -- :   Rendered layouts/_footer.html.haml (1.1ms)
I, [2020-01-28T22:50:13.455089 #24994]  INFO -- : Completed 500 Internal Server Error in 5ms (Views: 4.4ms)
I, [2020-01-28T22:50:13.457739 #24994]  INFO -- : Started GET "/ajax/classes/treeview?ontology=FEDORA&conceptid=root" for 171.66.184.249 at 2020-01-28 22:50:13 -0800
I, [2020-01-28T22:50:13.458476 #24994]  INFO -- : Processing by ConceptsController#show_tree as */*
I, [2020-01-28T22:50:13.458535 #24994]  INFO -- :   Parameters: {"ontology"=>"FEDORA", "conceptid"=>"root"}
I, [2020-01-28T22:50:13.694351 #24994]  INFO -- : Completed 500 Internal Server Error in 236ms
F, [2020-01-28T22:50:13.695017 #24994] FATAL -- :
F, [2020-01-28T22:50:13.695077 #24994] FATAL -- : NoMethodError (undefined method `first' for nil:NilClass):
F, [2020-01-28T22:50:13.695107 #24994] FATAL -- :
F, [2020-01-28T22:50:13.695132 #24994] FATAL -- : app/controllers/application_controller.rb:402:in `get_class'
app/controllers/concepts_controller.rb:82:in `show_tree'
I, [2020-01-28T22:50:13.695648 #24994]  INFO -- : Processing by ErrorsController#internal_server_error as */*
I, [2020-01-28T22:50:13.695703 #24994]  INFO -- :   Parameters: {"ontology"=>"FEDORA", "conceptid"=>"root"}
I, [2020-01-28T22:50:13.696984 #24994]  INFO -- :   Rendering errors/internal_server_error.html.erb within layouts/ontology
I, [2020-01-28T22:50:13.697261 #24994]  INFO -- :   Rendered errors/internal_server_error.html.erb within layouts/ontology (0.2ms)
I, [2020-01-28T22:50:13.699215 #24994]  INFO -- :   Rendered layouts/_topnav.html.haml (1.0ms)
I, [2020-01-28T22:50:13.699501 #24994]  INFO -- :   Rendered layouts/_notices.html.erb (0.1ms)
I, [2020-01-28T22:50:13.699583 #24994]  INFO -- :   Rendered layouts/_header.html.erb (2.1ms)
I, [2020-01-28T22:50:13.700735 #24994]  INFO -- :   Rendered application/_ga_tracking.html.haml (0.1ms)
I, [2020-01-28T22:50:13.700823 #24994]  INFO -- :   Rendered layouts/_footer.html.haml (1.1ms)
I, [2020-01-28T22:50:13.701049 #24994]  INFO -- : Completed 500 Internal Server Error in 5ms (Views: 4.3ms)
`

**Comment by graybeal** [comment]
so many things not to like in that last one. interesting that I recognized a lot of that sequence from the latest_submission trace I did in New Relic today, but the latest_submission error doesn't show up.  maybe that comes up in a separate attempt to display it...

**Comment by alexskr** [comment]
`undefined method first for nil:NilClass` errors that UI throws is in the top 5 errors list according to newrelic for the UI

**Comment by alexskr** [comment]
this problem also applies to ontologies that do not have any successfully parsed submissions.  
UI throws errors when summary or property page is hit.

bioportal should handle this case more gracefully or it should not even attempt to display thinks like properties, tree view or whatever else that requires properly parsed ontology
