### ISSUE TITLE
HIV: fails to parse

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#17]
Submission 2.6 of the [HIV ontology](http://bioportal.bioontology.org/ontologies/HIV), uploaded on March 20, 2017 failed to parse.  BioPortal UI shows status of "Error Rdf".

Preliminary investigation shows several issues:

1.  The user incorrectly designated the submission file format as OWL when it should be OBO.  This shouldn't affect the parsing step though.  The format should be corrected when the next submission is created.

2. Line 2 of their ontology source file uses an incorrect date format.  The [OBO Flat File Format Guide](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html) states that dates must be in a format of dd:MM:yyyy HH:mm.  If you parse this ontology with version 4.2.5 of the OWL API, this exception is thrown:

```
Parser: org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser@3888cf9
    Stack trace:
LINENO: 2 - Could not parse date from string: December 27, 2016
LINE: date: December 27, 2016        org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:60)
```

To fix this exception, change line 2 of the ontology source file to this:

```
date: 27:12:2016 00:00
```

3. After fixing line 2 of the ontology, re-parsing results in further errors, e.g.:

```
Parser: org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser@15563bcf
    Stack trace:
LINENO: 38 - Could not find tag for: part_of
LINE: part_of: HIV:29 ! retrovirus        org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:60)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:197)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:967)
        edu.stanford.ncbo.bioportal.SimpleLoadTest.testLoadHIVOntology_WithDocumentFormat(SimpleLoadTest.java:50)
        sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:606)
``` 

These exceptions are thrown with version 4.2.5 of the OWL API, which BioPortal currently uses internally.  Version 4.2.6 (and above) of the OWL API successfully parse the ontology with no exceptions.  The user reported that they could open the ontology in the Protege ontology editor without issues.  The latest version of Protege (5.2.0) uses version 4.2.8 of the OWL API, thus the lack of issue opening the HIV ontology in their environment.

**Comment by jvendetti** [comment]
I corresponded with Ignazio (current principle developer of the OWL API), and the conclusion is that the API detects this ontology as on older OBO format (version 1.2).  In order for our system to parse the ontology, we need to include the [owl-compatibility](https://search.maven.org/#search%7Cga%7C1%7Cowlapi-compatibility) module of the OWL API, which allows for parsing of older OBO formats.  

I upgraded the [owlapi_wrapper to use version 4.3.1 of the OWL API](https://github.com/ncbo/owlapi_wrapper/issues/5) (with the compatibility module added), and also performed a new release of the BioPortal back-end code that includes the new owlapi_wrapper JAR file.

**Comment by jvendetti** [comment]
After upgrading our system to a new OWLAPI version, the ontology is successfully loaded into memory, but fails the second parsing step where we serialize to RDF/XML format:

```
"RestClient::BadRequest: 400 Bad Request
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.1/lib/restclient/abstract_response.rb:223:in `exception_with_response'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.1/lib/restclient/abstract_response.rb:103:in `return!'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:809:in `process_result'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:725:in `block in transmit'
/usr/local/rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:715:in `transmit'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:145:in `execute'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:52:in `execute'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-f9454b16d012/lib/goo/sparql/client.rb:102:in `append_triples_no_bnodes'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-f9454b16d012/lib/goo/sparql/client.rb:128:in `put_triples'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-c37c5c4959d1/lib/ontologies_linked_data/models/ontology_submission.rb:1411:in `delete_and_append'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-c37c5c4959d1/lib/ontologies_linked_data/models/ontology_submission.rb:438:in `generate_rdf'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-c37c5c4959d1/lib/ontologies_linked_data/models/ontology_submission.rb:892:in `process_submission'
/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:177:in `process_submission'
```

This turned out to be an issue with missing underscores in some of the OBO tags in the source file.  On line 296, the “preceded_by” tag is missing an underscore, and on lines 944, 963, 972, and 981, the “property_value” tag is missing underscores.  Fixed these manually in the copy on our server and reparsed.  The ontology now shows as parsed in BioPortal, but trying to navigate to the Classes tab results in a 404.

**Comment by jvendetti** [comment]
Running the UI in my local dev environment shows a missing roots error:

```
Started GET "/ajax/classes/treeview?ontology=HIV&conceptid=root" for ::1 at 2017-04-12 14:59:41 -0700
Processing by ConceptsController#show_tree as */*
  Parameters: {"ontology"=>"HIV", "conceptid"=>"root"}
Missing roots for HIV
  Rendered text template (0.1ms)
Completed 500 Internal Server Error in 2233ms (Views: 22.1ms | ActiveRecord: 0.0ms)
```

I looked at the [owlapi.xrdf](https://github.com/ncbo/bioportal-project/files/923086/owlapi.xrdf.zip) file that we generate for this ontology.  It's a valid RDF file, but only contains data for properties and individuals.  All class data is missing.

Some initial debugging in the owlapi_wrapper code indicates that the [generateSKOSInObo](https://github.com/ncbo/owlapi_wrapper/blob/master/src/main/java/org/stanford/ncbo/oapiwrapper/OntologyParser.java#L400) method marks all classes in this ontology for deletion.  The method is undocumented - needs further investigation.

**Comment by jvendetti** [comment]
It looks like the generateSkosInObo method identifies classes by checking for "#id" in annotation property strings.  If "#id" is found, the subject of the annotation is retrieved and stored.  In the case of the HIV ontology, these property strings end in "#xref" instead of "#id".  We should add a check for this case and do a new release of the [owlapi_wrapper](https://github.com/ncbo/owlapi_wrapper).

**Comment by jvendetti** [comment]
Rewrote the algorithm in the generateSKOSInObo method so that it no longer marks valid OBO classes for deletion. This code went into the [1.3.2 release of the owlapi_wrapper](https://github.com/ncbo/owlapi_wrapper/releases/tag/v1.3.2). Performed a BioPortal backend release with this new version bundled. The class tree for HIV is now visible in BioPortal.
