### ISSUE TITLE
SWO: latest submission failed to parse

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#2]
The latest upload of this ontology (from February 8, 2017) failed to parse.  It passes the first step in the parsing process, i.e., it's successfully loaded by the OWL API, but fails the second step where the owlapi.xrdf file is fed to the rapper RDF parser.

Error from production parsing log:

```
E, [2017-02-08T18:22:36.069911 #12516] ERROR -- : Exception: Rapper cannot parse rdfxml file at /srv/ncbo/repository/SWO/26/owlapi.xrdf: rapper: Parsing URI file:///srv/ncbo/repository/SWO/26/owlapi.xrdf with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Error - URI file:///srv/ncbo/repository/SWO/26/owlapi.xrdf:68258 - Illegal rdf:nodeID value '_:genid51'
rapper: Parsing returned 40607 triples

/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/bundler/gems/goo-c8cc22b62c09/lib/goo/sparql/client.rb:59:in `bnodes_filter_file'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/bundler/gems/goo-c8cc22b62c09/lib/goo/sparql/client.rb:80:in `append_triples_no_bnodes'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/bundler/gems/goo-c8cc22b62c09/lib/goo/sparql/client.rb:128:in `put_triples'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/bundler/gems/ontologies_linked_data-5985b89b7b60/lib/ontologies_linked_data/models/ontology_submission.rb:1239:in `delete_and_append'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/bundler/gems/ontologies_linked_data-5985b89b7b60/lib/ontologies_linked_data/models/ontology_submission.rb:407:in `generate_rdf'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/bundler/gems/ontologies_linked_data-5985b89b7b60/lib/ontologies_linked_data/models/ontology_submission.rb:824:in `process_submission'
        /srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:178:in `process_submission'
        /srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:47:in `block in process_queue_submissions'
        /srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:40:in `each'
        /srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:40:in `process_queue_submissions'
        /srv/ncbo/ncbo_cron/bin/ncbo_cron:228:in `block (3 levels) in <main>'
        /srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:65:in `block (3 levels) in scheduled_locking_job'
        /srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:51:in `fork'
        /srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:51:in `block (2 levels) in scheduled_locking_job'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/gems/mlanett-redis-lock-0.2.7/lib/redis-lock.rb:43:in `call'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/gems/mlanett-redis-lock-0.2.7/lib/redis-lock.rb:43:in `lock'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/gems/mlanett-redis-lock-0.2.7/lib/redis-lock.rb:234:in `lock'
        /srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:50:in `block in scheduled_locking_job'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
        /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
```

**Comment by jvendetti** [comment]
In the original ontology source file (swo_inferred.owl), there's an annotation on an annotation that contains a blank <rdf:Description> element.  See relevant snippet beginning on line 64,575:

```
<swo:SWO_0000144>
  <rdf:Description/>
</swo:SWO_0000144>
```

When the OWL API loads the ontology, it generates an ID for this blank element, i.e.:

```
<rdf:Description rdf:nodeID="_:genid28"/>
```

When we serialize this ontology to RDF/XML format, the generated ID gets saved in the owlapi.xrdf file that we create every time we parse an ontology.  When the owlapi.xrdf file is fed to the rapper RDF parser to create the triples, it won't accept this generated ID as valid RDF.  Apparently RDF node IDs can't contain the ':' character.

I removed the blank element, reparsed the ontology in production, and it's accessible in BioPortal now.  The last 3 uploads of this ontology have failed due to the same error (documented in BioPortal's old private issue tracker as NCBO-1825).  We should contact the ontology authors to see if they'd be willing to fix the source file to circumvent these parsing failures in the future.

**Comment by jvendetti** [comment]
The latest version of this ontology parsed successfully because we upgraded BioPortal to version 4.3.2 of the OWL API. This version contains a fix for the generation of invalid blank node identifiers, e.g., "_:genid28", as mentioned above. See https://github.com/owlcs/owlapi/issues/689 for details.
