### ISSUE TITLE
Diff is failing for AFO ontology

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#219]
Received a report from end user that [AFO](https://bioportal.bioontology.org/ontologies/AFO) is displaying an "Error Diff" status on the summary page.

Stack trace from parsing log:

```
I, [2021-10-11T10:28:55.430441 #23475]  INFO -- : ["Java call [java -DentityExpansionLimit=1500000 -Xmx5120M -jar /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-c4562ccb355a/bin/bubastis.jar -ontology1 /srv/ncbo/repository/AFO/19/merged-without-qudt.ttl -ontology2 /srv/ncbo/repository/AFO/20/merged-without-qudt-and-inferred.ttl -output /srv/ncbo/repository/AFO/20/bubastis_diff.xml -format xml]"]
I, [2021-10-11T10:28:55.888639 #23475]  INFO -- : ["Bubastis diff finished OK."]
I, [2021-10-11T10:28:55.888695 #23475]  INFO -- : ["Performing diff failed.  Reason: null"]
I, [2021-10-11T10:28:55.888753 #23475]  INFO -- : ["ontology 1 is a file /srv/ncbo/repository/AFO/19/merged-without-qudt.ttl
ontology 2 is a file /srv/ncbo/repository/AFO/20/merged-without-qudt-and-inferred.ttl
trying load now"]
E, [2021-10-11T10:28:55.889135 #23475] ERROR -- : ["Bubastis diff for http://data.bioontology.org/ontologies/AFO/submissions/20 failed - LinkedData::Diff::BubastisDiffException: Bubastis diff command exited with status=0. Output file /srv/ncbo/repository/AFO/20/bubastis_diff.xml cannot be found."]
E, [2021-10-11T10:28:55.889293 #23475] ERROR -- : ["LinkedData::Diff::BubastisDiffException: Bubastis diff command exited with status=0. Output file /srv/ncbo/repository/AFO/20/bubastis_diff.xml cannot be found.
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-c4562ccb355a/lib/ontologies_linked_data/diff/bubastis_diff.rb:100:in `call_bubastis_java_cmd'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-c4562ccb355a/lib/ontologies_linked_data/diff/bubastis_diff.rb:114:in `diff'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-c4562ccb355a/lib/ontologies_linked_data/models/ontology_submission.rb:340:in `diff'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-c4562ccb355a/lib/ontologies_linked_data/models/ontology_submission.rb:1090:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:177:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:47:in `block in process_queue_submissions'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:41:in `each'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:41:in `process_queue_submissions'
	/srv/ncbo/ncbo_cron/bin/ncbo_cron:246:in `block (3 levels) in <main>'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:65:in `block (3 levels) in scheduled_locking_job'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:51:in `fork'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:51:in `block (2 levels) in scheduled_locking_job'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/gems/mlanett-redis-lock-0.2.7/lib/redis-lock.rb:43:in `lock'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/gems/mlanett-redis-lock-0.2.7/lib/redis-lock.rb:234:in `lock'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:50:in `block in scheduled_locking_job'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'"]
```

**Comment by jvendetti** [comment]
Performed the following:

* Downloaded ontology source files from the last two submissions (numbers 22 and 23)
* Used my local copy of the bubastis JAR file to generate a diff file (diff succeeded w/out errors)
* Uploaded the resulting bubastis_diff.xml file to production
* For submission 23:
  * Set the diffFilePath attribute
  * Removed the "ERROR_DIFF" status
  * Added the "DIFF" status
