### ISSUE TITLE
AG:  Error during ontologies report paging - ArgumentError: Not supported case for embed

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal-project#254]
getting `Error during ontologies report paging - ArgumentError: Not supported case for embed` when processing with AllegroGraph backend for the following ontologies:

CIDIT_V1
CLO
ORDO_OBO
UPHENO
BIOMODELS
MHCRO
CCS_DIFF_CON_ANC
CHEAR
LION
ZP
XREF-FUNDER-REG
CCONT
RH-MESH
WB-BT
GO
HOIP
OGG
CIDIO_AUX
I2B2-LOINC

tracestack:
```
E, [2022-08-25T00:33:22.524952 #4829] ERROR -- : ["Error during ontologies report paging - ArgumentError: Not supported case for embed\n/srv/ncbo/ncbo_cron_ag/vendor/bundle/ruby/2.7.0/bundler/gems/goo-562826ba21f7/lib/goo/sparql/queries.rb:426:in `model_load_sliced'\n/srv/ncbo/ncbo_cron_ag/vendor/bundle/ruby/2.7.0/bundler/gems/goo-562826ba21f7/lib/goo/sparql/queries.rb:265:in `block in model_load'\n/srv/ncbo/ncbo_cron_ag/vendor/bundle/ruby/2.7.0/bundler/gems/goo-562826ba21f7/lib/goo/sparql/queries.rb:260:in `each'\n/srv/ncbo/ncbo_cron_ag/vendor/bundle/ruby/2.7.0/bundler/gems/goo-562826ba21f7/lib/goo/sparql/queries.rb:260:in `each_slice'\n/srv/ncbo/ncbo_cron_ag/vendor/bundle/ruby/2.7.0/bundler/gems/goo-562826ba21f7/lib/goo/sparql/queries.rb:260:in `model_load'\n/srv/ncbo/ncbo_cron_ag/vendor/bundle/ruby/2.7.0/bundler/gems/goo-562826ba21f7/lib/goo/base/where.rb:214:in `process_query_intl'\n/srv/ncbo/ncbo_cron_ag/vendor/bundle/ruby/2.7.0/bundler/gems/goo-562826ba21f7/lib/goo/base/where.rb:131:in `process_query'\n/srv/ncbo/ncbo_cron_ag/vendor/bundle/ruby/2.7.0/bundler/gems/goo-562826ba21f7/lib/goo/base/where.rb:282:in `all'\n/srv/ncbo/ncbo_cron_ag/lib/ncbo_cron/ontologies_report.rb:357:in `good_classes'\n/srv/ncbo/ncbo_cron_ag/lib/ncbo_cron/ontologies_report.rb:295:in `generate_single_ontology_report'\n/srv/ncbo/ncbo_cron_ag/lib/ncbo_cron/ontologies_report.rb:76:in `block (2 levels) in refresh_report'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'\n/srv/ncbo/ncbo_cron_ag/lib/ncbo_cron/ontologies_report.rb:75:in `block in refresh_report'\n/srv/ncbo/ncbo_cron_ag/lib/ncbo_cron/ontologies_report.rb:72:in `each'\n/srv/ncbo/ncbo_cron_ag/lib/ncbo_cron/ontologies_report.rb:72:in `refresh_report'\n/srv/ncbo/ncbo_cron_ag/lib/ncbo_cron/ontology_submission_parser.rb:187:in `process_submission'\nbin/ncbo_ontology_process:98:in `block in <top (required)>'\nbin/ncbo_ontology_process:81:in `each'\nbin/ncbo_ontology_process:81:in `<top (required)>'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `load'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `kernel_load'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:23:in `run'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli.rb:483:in `exec'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli.rb:31:in `dispatch'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli.rb:25:in `start'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/exe/bundle:48:in `block in <top (required)>'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'\n/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/exe/bundle:36:in `<top (required)>'\n/usr/local/rbenv/versions/2.7.6/bin/bundle:23:in `load'\n/usr/local/rbenv/versions/2.7.6/bin/bundle:23:in `<main>'"]
```

**Comment by mdorf** [comment]
I am unable to reproduce this error.

**Comment by syphax-bouazzouni** [comment]
Hi, 
My following remark is maybe not directly related to the issue

In this [line](https://github.com/ncbo/ncbo_cron/blob/master/lib/ncbo_cron/ontologies_report.rb#L348)

```ruby
 paging = LinkedData::Models::Class.in(submission).include(:prefLabel, :synonym, metrics: :classes).page(page_num, page_size)
```
We include the embedded `metrics` attribute for the model `Class`, although it doesn't have it. It's the `ÒntologySubmission` that provides it. This means that the previous request need to be like this 

```ruby
 paging = LinkedData::Models::Class.in(submission).include(:prefLabel, :synonym, submission: [metrics: [:classes]]).page(page_num, page_size)
```

**Comment by mdorf** [comment]
> Hi, My following remark is maybe not directly related to the issue
> 
> In this [line](https://github.com/ncbo/ncbo_cron/blob/master/lib/ncbo_cron/ontologies_report.rb#L348)
> 
> ```ruby
>  paging = LinkedData::Models::Class.in(submission).include(:prefLabel, :synonym, metrics: :classes).page(page_num, page_size)
> ```
> 
> We include the embedded `metrics` attribute for the model `Class`, although it doesn't have it. It's the `ÒntologySubmission` that provides it. This means that the previous request need to be like this
> 
> ```ruby
>  paging = LinkedData::Models::Class.in(submission).include(:prefLabel, :synonym, submission: [metrics: [:classes]]).page(page_num, page_size)
> ```

Good catch, I'll fix this in the code.
