### ISSUE TITLE
NEUROBRG: failed to process

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#295]
From the support list:

> I would like to request your help regarding one of our metadata ontology listed in BioPortal (NeuroBridge Ontology), which seems to be inaccessible to users: https://bioportal.bioontology.org/ontologies/NEUROBRG. Can you please clarify if the ontology OWL file has any parsing or other errors? I will be happy to edit the OWL file as necessary.

Full stack trace from production logs:

```
E, [2023-11-16T08:52:25.929947 #29240] ERROR -- : ["Error sending data to triple store - 400 RestClient::BadRequest: MALFORMED DATA: Turtle* parser error while parsing an input stream on or around line 6: Can't parse to production statement"]
E, [2023-11-16T08:52:25.930094 #29240] ERROR -- : ["RestClient::BadRequest: 400 Bad Request
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
\t/usr/local/rbenv/versions/2.7.7/lib/ruby/2.7.0/net/http.rb:933:in `start'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/goo-657149d6b338/lib/goo/sparql/client.rb:116:in `append_triples_no_bnodes'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/goo-657149d6b338/lib/goo/sparql/client.rb:141:in `put_triples'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-7783784f9d2c/lib/ontologies_linked_data/models/ontology_submission.rb:1638:in `delete_and_append'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-7783784f9d2c/lib/ontologies_linked_data/models/ontology_submission.rb:490:in `generate_rdf'
\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-7783784f9d2c/lib/ontologies_linked_data/models/ontology_submission.rb:1015:in `process_submission'
\t/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:178:in `process_submission'
```

**Comment by jvendetti** [comment]
I believe the issue is an invalid value for the language tag on line 16 of the ontology source file:

```
<prov:editorialNote xml:lang="osumc.edu">Contact: satya.sahoo@case.edu, Lei.Wang@osumc.edu</prov:editorialNote>
```

I've asked the user to correct this and resubmit.

**Comment by jvendetti** [comment]
User resubmitted with corrected language tag value and the ontology was successfully reprocessed
