### ISSUE TITLE
NMDCO: latest submission (with ID 5) fails to parse

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#306]
Full stack trace:

```
E, [2024-02-15T19:11:40.991079 #8037] ERROR -- : ["Error sending data to triple store - 400 RestClient::BadRequest: MALFORMED DATA: `2023-08-25T:17:42.901Z` is not of type xsd:dateTime, There's junk in this string: \"2023-08-25T:17:42.901Z\"."]
E, [2024-02-15T19:11:40.991363 #8037] ERROR -- : ["RestClient::BadRequest: 400 Bad Request
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
	/usr/local/rbenv/versions/2.7.7/lib/ruby/2.7.0/net/http.rb:933:in `start'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/goo-75436fe8e387/lib/goo/sparql/client.rb:116:in `append_triples_no_bnodes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/goo-75436fe8e387/lib/goo/sparql/client.rb:141:in `put_triples'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-0003905c5d10/lib/ontologies_linked_data/models/ontology_submission.rb:1645:in `delete_and_append'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-0003905c5d10/lib/ontologies_linked_data/models/ontology_submission.rb:497:in `generate_rdf'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-0003905c5d10/lib/ontologies_linked_data/models/ontology_submission.rb:1022:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:171:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:45:in `block in process_queue_submissions'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:25:in `each'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:25:in `process_queue_submissions'
```

**Comment by jvendetti** [comment]
This ontology has three classes (stream pool, step pool, and stream run) where the creation_date property contains an invalid `xsd:dateTime` value. To follow is a screen shot in Protege, which shows one of the invalid values in red:

<br>
<img width="995" alt="Screenshot 2024-02-16 at 11 46 44 AM" src="https://github.com/ncbo/bioportal-project/assets/1696923/fcb6e732-b980-474c-a70c-ffad8a926157">
<br><br>

I corrected these values and uploaded a new copy of the ontology to our staging environment, where it processed successfully.

**Comment by turbomam** [comment]
- https://github.com/EnvironmentOntology/envo/issues/1493

**Comment by turbomam** [comment]
This can be closed now. Thanks for the help.
