### ISSUE TITLE
ENVO: latest submission (with ID 58) fails to parse

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#307]
Full stack trace:

```
E, [2024-02-07T18:05:53.336115 #13879] ERROR -- : ["Error sending data to triple store - 400 RestClient::BadRequest: MALFORMED DATA: `2023-08-25T:17:42.901Z` is not of type xsd:dateTime, There's junk in this string: \"2023-08-25T:17:42.901Z\"."]
E, [2024-02-07T18:05:53.336560 #13879] ERROR -- : ["RestClient::BadRequest: 400 Bad Request
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
	/usr/local/rbenv/versions/2.7.7/lib/ruby/2.7.0/net/http.rb:933:in `start'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/goo-75436fe8e387/lib/goo/sparql/client.rb:116:in `append_triples_no_bnodes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/goo-75436fe8e387/lib/goo/sparql/client.rb:141:in `put_triples'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-8319482644c5/lib/ontologies_linked_data/models/ontology_submission.rb:1645:in `delete_and_append'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-8319482644c5/lib/ontologies_linked_data/models/ontology_submission.rb:497:in `generate_rdf'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-8319482644c5/lib/ontologies_linked_data/models/ontology_submission.rb:1022:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:171:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:45:in `block in process_queue_submissions'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:25:in `each'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:25:in `process_queue_submissions'
```

**Comment by jvendetti** [comment]
This ontology has three classes (stream pool, step pool, and stream run) where the `creation_date` annotation property has an invalid xsd:dateTime value. The following screen shot shows one of the invalid values highlighted in red in Protege:

<br>
<img width="763" alt="Screenshot 2024-02-16 at 12 49 07 PM" src="https://github.com/ncbo/bioportal-project/assets/1696923/fe68ed53-0533-440b-b4a5-ba0ed159b789">

**Comment by jvendetti** [comment]
Fixed by ontology maintainer. Subsequent submission (ID 59) processed successfully.
