### ISSUE TITLE
MONDO: failing to pull new versions since May

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#329]
We're currently serving version "releases/2024-05-08" of [MONDO](https://bioportal.bioontology.org/ontologies/MONDO). The pull URL is configured as http://purl.obolibrary.org/obo/mondo.obo. Since May there have been six new releases of MONDO that don't appear in BioPortal.

The error log output in `/srv/ncbo/repository/MONDO/64` is:

```
++++++++++++++++++++++++++++++++++++++++++++++++++
Error: OWL_STORAGE_EXCEPTION
Message: Error buildOWLOntologyhttp://www.geneontology.org/formats/oboInOwl#IAO:0000116
++++++++++++++++++++++++++++++++++++++++++++++++++
```

Attempting an on-demand pull, i.e. `bin/ncbo_ontology_pull -o MONDO` results in:

```
E, [2024-11-12T13:54:59.172741 #2024919] ERROR -- : The new file for ontology MONDO, submission id: 64 did not clear OWLAPI: LinkedData::Parser::OWLAPIParserException: OWLAPI java command exited with  0. Output file /srv/ncbo/repository/MONDO/64/owlapi.xrdf cannot be found.
/srv/ontoportal/ncbo_cron/vendor/bundle/ruby/3.0.0/bundler/gems/ontologies_linked_data-883344784ef9/lib/ontologies_linked_data/parser/owlapi.rb:126:in `block in call_owlapi_java_command'
        /usr/local/rbenv/versions/3.0.6/lib/ruby/3.0.0/open3.rb:227:in `popen_run'
        /usr/local/rbenv/versions/3.0.6/lib/ruby/3.0.0/open3.rb:102:in `popen3'
        /srv/ontoportal/ncbo_cron/vendor/bundle/ruby/3.0.0/bundler/gems/ontologies_linked_data-883344784ef9/lib/ontologies_linked_data/parser/owlapi.rb:77:in `call_owlapi_java_command'
        /srv/ontoportal/ncbo_cron/vendor/bundle/ruby/3.0.0/bundler/gems/ontologies_linked_data-883344784ef9/lib/ontologies_linked_data/parser/owlapi.rb:154:in `parse'
        /srv/ontoportal/ncbo_cron/lib/ncbo_cron/ontology_helper.rb:116:in `create_submission'
        /srv/ontoportal/ncbo_cron/lib/ncbo_cron/ontology_helper.rb:64:in `do_ontology_pull'
        bin/ncbo_ontology_pull:37:in `<main>'
E, [2024-11-12T13:54:59.172813 #2024919] ERROR -- : A new submission has NOT been created.
```

**Comment by jvendetti** [comment]
The failure is occurring in the [owlapi_wrapper](https://github.com/ncbo/owlapi_wrapper) code when it attempts to [serialize the ontology to RDF/XML format](https://github.com/ncbo/owlapi_wrapper/blob/2856e0ba6675b4e817ee5b92d783ad96a37b3d5c/src/main/java/org/stanford/ncbo/owlapi/wrapper/OntologyParser.java#L576) in the `serializeOntology()` method. The cause value of the exception is:

```
org.semanticweb.owlapi.rdf.rdfxml.renderer.IllegalElementNameException: Illegal Element Name (Element Is Not A QName): http://www.geneontology.org/formats/oboInOwl#IAO:0000116
```

The serialization step completes for the May 8th release of MONDO, but not for the November release. There hasn't been a release of the `owlapi_wrapper` project in just over a year. MONDO is a big ontology, and it's not immediately evident to me what the difference is that's resulting in the serialization failure.

<img width="1739" alt="Screenshot 2024-11-12 at 4 53 32 PM" src="https://github.com/user-attachments/assets/2067721d-9f6c-4dfd-aad1-b764b1c1c896">

**Comment by jvendetti** [comment]
FWIW, I've written some simple OWL API code outside of the BioPortal stack to test if the OBO file can be serialized to RDF/XML format:

```java
// Load the November release of MONDO (data-version: releases/2024-11-05)
File file = new File("src/test/resources/mondo/mondo.obo");
IRI iri = IRI.create(file);
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology ontology = manager.loadOntology(iri);

// Attempt to serialize MONDO to RDF/XML format
File file1 = new File("src/test/resources/mondo/mondo.xrdf");
IRI iri1 = IRI.create(file1);
manager.saveOntology(ontology, new RDFXMLDocumentFormat(), iri1);
```

The code above succeeds.

I can also use the Protege application (version 5.6.4) to successfully save the OBO file to RDF/XML.

**Comment by jvendetti** [comment]
Per @cmungall, I modified the pull URL for this ontology to use a simplified version (http://purl.obolibrary.org/obo/mondo/mondo-simple.obo). BioPortal was able to ingest this version without any issues, and is now serving the Nov. 5th release.
