### ISSUE TITLE
PLANA: not accessible in BioPortal user interface

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#43]
Navigating to the [PLANA ontology](http://bioportal.bioontology.org/ontologies/PLANA) in the BioPortal UI results in a 500 error.

**Comment by jvendetti** [comment]
Error is occurring at the REST API level. Calls to the submissions endpoint result in:

```
D, [2017-09-22T12:33:56.800759 #6383] DEBUG -- : undefined method `acronym' for nil:NilClass
```

**Comment by jvendetti** [comment]
Latest submission object for this ontology is corrupt:

```
[5] pry(main)> sub.valid?
=> false
[6] pry(main)> sub.errors
=> {:hasOntologyLanguage=>{:existence=>"`hasOntologyLanguage` value cannot be nil"},
 :contact=>{:existence=>"`contact` value cannot be nil"},
 :released=>{:existence=>"`released` value cannot be nil"},
 :ontology=>{:existence=>"`ontology` value cannot be nil"}}
```

**Comment by jvendetti** [comment]
Deleted the corrupt submission with ID 2 manually from an ncbo_cron console session. The UI still showed a 500 error because the latest submission with ID 3, though valid, had a nil value in the creationDate attribute. This caused the UI to fail with the following error:

```
Completed 500 Internal Server Error in 1067ms (ActiveRecord: 0.0ms)

ActionView::Template::Error (invalid date):
    56:       %td
    57:         = xmldatetime_to_date(sub.released) unless sub.released.nil?
    58:       %td
    59:         = xmldatetime_to_date(sub.creationDate)
    60:       - unless ont_restricted
    61:         %td
    62:           = raw download_link(sub)
  app/helpers/application_helper.rb:386:in `xmlschema'
  app/helpers/application_helper.rb:386:in `xmldatetime_to_date'
  app/views/ontologies/_submissions.html.haml:59:in `block in _app_views_ontologies__submissions_html_haml___2188683596160157506_70347375202440'
  app/views/ontologies/_submissions.html.haml:51:in `each'
  app/views/ontologies/_submissions.html.haml:51:in `each_with_index'
  app/views/ontologies/_submissions.html.haml:51:in `_app_views_ontologies__submissions_html_haml___2188683596160157506_70347375202440'
  app/views/ontologies/_metadata.html.haml:9:in `_app_views_ontologies__metadata_html_haml__2673866346802809260_70347384723760'
  app/controllers/ontologies_controller.rb:385:in `summary'
  app/controllers/ontologies_controller.rb:349:in `show'
```

Manually initialized the creationDate attribute, which fixed the error. Ontology now displays properly in the UI. It's unclear how the submission object made it into the triplestore without a creation date, since this attribute is [marked as required](https://github.com/ncbo/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology_submission.rb#L38) in the OntologySubmission class.

On a related note, I added a new submission for this ontology to use the pull URL specified in the OBO Foundry. (We're in the process of syncing BioPortal and OBO Foundry wherever possible for content serving).
