### ISSUE TITLE
ONTONEO: last 4 submissions failed to parse

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#50]
The lastest 4 submissions for [ONTONEO](http://bioportal.bioontology.org/ontologies/ONTONEO) failed to parse. Error from parsing.log file:

```
E, [2017-08-03T19:13:05.004447 #2608] ERROR -- : ["Exception: Rapper cannot parse rdfxml file at /srv/ncbo/repository/ONTONEO/10/owlapi.xrdf: 
rapper: Parsing URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:21075 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:21095 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:21217 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:21371 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:21374 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:38750 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:38751 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:41892 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:42356 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:42374 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:42390 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:42446 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:42447 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:42489 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:42490 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:42518 - rdf:comment is an unknown RDF namespaced element.
rapper: Warning - URI file:///srv/ncbo/repository/ONTONEO/10/owlapi.xrdf:42682 - rdf:comment is an unknown RDF namespaced element.
rapper: Parsing returned 28845 triples

/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-dd1b78375bae/lib/goo/sparql/client.rb:59:in `bnodes_filter_file'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-dd1b78375bae/lib/goo/sparql/client.rb:80:in `append_triples_no_bnodes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-dd1b78375bae/lib/goo/sparql/client.rb:128:in `put_triples'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-5d17205300d9/lib/ontologies_linked_data/models/ontology_submission.rb:1415:in `delete_and_append'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-5d17205300d9/lib/ontologies_linked_data/models/ontology_submission.rb:438:in `generate_rdf'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-5d17205300d9/lib/ontologies_linked_data/models/ontology_submission.rb:892:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:177:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:47:in `block in process_queue_submissions'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:41:in `each'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:41:in `process_queue_submissions'
	/srv/ncbo/ncbo_cron/bin/ncbo_cron:228:in `block (3 levels) in <main>'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:65:in `block (3 levels) in scheduled_locking_job'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:51:in `fork'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:51:in `block (2 levels) in scheduled_locking_job'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/mlanett-redis-lock-0.2.7/lib/redis-lock.rb:43:in `lock'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/mlanett-redis-lock-0.2.7/lib/redis-lock.rb:234:in `lock'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:50:in `block in scheduled_locking_job'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'"]
```

**Comment by jvendetti** [comment]
Ontology source file contained 34 occurrences of rdf:comment tags. These should be rdfs:comment (hence the error message above "rdf:comment is an unknown RDF namespaced element". I modified all occurrences to be rdfs:comment and reprocessed. Ontology parsed without errors and loaded into the triplestore. I entered an issue in their tracker, asking for this modification to be made directly in their source file. Until we get a response, I disabled the pull URL for this ontology so BioPortal won't pull new versions and repeat the parsing failures. I also deleted the bad submissions.
