### ISSUE TITLE
ONTOPARON_SOCIAL: loading data into the triplestore fails

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#57]
The [ONTOPARON_SOCIAL](http://bioportal.bioontology.org/ontologies/ONTOPARON_SOCIAL) ontology passes the OWL API parsing phase, but the Ruby code that loads the data into the triplestore fails. Full stack trace from the log:

```
E, [2017-12-01T11:10:15.997478 #32467] ERROR -- : ["RestClient::BadRequest: 400 Bad Request
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
	/usr/local/rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-59f145cdae84/lib/goo/sparql/client.rb:102:in `append_triples_no_bnodes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-59f145cdae84/lib/goo/sparql/client.rb:128:in `put_triples'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-33015eba8641/lib/ontologies_linked_data/models/ontology_submission.rb:1424:in `delete_and_append'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-33015eba8641/lib/ontologies_linked_data/models/ontology_submission.rb:449:in `generate_rdf'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-33015eba8641/lib/ontologies_linked_data/models/ontology_submission.rb:903:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:177:in `process_submission'
	bin/ncbo_ontology_process:98:in `block in <main>'
	bin/ncbo_ontology_process:81:in `each'
	bin/ncbo_ontology_process:81:in `<main>'"]
E, [2017-12-01T11:10:16.101399 #32467] ERROR -- : Failed, exception: RestClient::BadRequest: 400 Bad Request
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/usr/local/rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-59f145cdae84/lib/goo/sparql/client.rb:102:in `append_triples_no_bnodes'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-59f145cdae84/lib/goo/sparql/client.rb:128:in `put_triples'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-33015eba8641/lib/ontologies_linked_data/models/ontology_submission.rb:1424:in `delete_and_append'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-33015eba8641/lib/ontologies_linked_data/models/ontology_submission.rb:449:in `generate_rdf'
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-33015eba8641/lib/ontologies_linked_data/models/ontology_submission.rb:903:in `process_submission'
/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:177:in `process_submission'
bin/ncbo_ontology_process:98:in `block in <main>'
bin/ncbo_ontology_process:81:in `each'
bin/ncbo_ontology_process:81:in `<main>'
```

Historically, this error has turned up when the code tries to load malformed ntriples data into the triplestore. I manually ran some rapper commands on ncboprod-parser1, but the output didn't indicate any issues with the ntriples data:

```
[ncbo-deployer@ncbo-prd-app-25 1]$ pwd
/srv/ncbo/repository/ONTOPARON_SOCIAL/1

[ncbo-deployer@ncbo-prd-app-25 1]$ rapper -i rdfxml -o ntriples owlapi.xrdf > data.triples
rapper: Parsing URI file:///srv/ncbo/share/env/production/repository/ONTOPARON_SOCIAL/1/owlapi.xrdf with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Parsing returned 8691 triples

[ncbo-deployer@ncbo-prd-app-25 1]$ rapper -i ntriples -c data.triples
rapper: Parsing URI file:///srv/ncbo/share/env/production/repository/ONTOPARON_SOCIAL/1/data.triples with parser ntriples
rapper: Parsing returned 8691 triples
```

Protege loads this ontology without errors.

**Comment by jvendetti** [comment]
User contacted us to say that he thought the initial submission of this ontology may have annotations that are not described with a full URI. He submitted another version (submission ID 2), but the results in our system are the same. The OWL API handles this submission without error, but we're unable to load it into the triplestore. Same error message in the log file:

```
E, [2017-12-04T10:28:27.133044 #6450] ERROR -- : ["RestClient::BadRequest: 400 Bad Request
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
	/usr/local/rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-59f145cdae84/lib/goo/sparql/client.rb:102:in `append_triples_no_bnodes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-59f145cdae84/lib/goo/sparql/client.rb:128:in `put_triples'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-33015eba8641/lib/ontologies_linked_data/models/ontology_submission.rb:1424:in `delete_and_append'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-33015eba8641/lib/ontologies_linked_data/models/ontology_submission.rb:449:in `generate_rdf'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-33015eba8641/lib/ontologies_linked_data/models/ontology_submission.rb:903:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:177:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:47:in `block in process_queue_submissions'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:41:in `each'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:41:in `process_queue_submissions'
	/srv/ncbo/ncbo_cron/bin/ncbo_cron:234:in `block (3 levels) in <main>'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:65:in `block (3 levels) in scheduled_locking_job'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:51:in `fork'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:51:in `block (2 levels) in scheduled_locking_job'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/mlanett-redis-lock-0.2.7/lib/redis-lock.rb:43:in `lock'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/mlanett-redis-lock-0.2.7/lib/redis-lock.rb:234:in `lock'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/scheduler.rb:50:in `block in scheduled_locking_job'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'"]
```

... and same results from a manual run of rapper commands to check for malformed ntriples data:

```
[ncbo-deployer@ncbo-prd-app-25 2]$ rapper -i rdfxml -o ntriples owlapi.xrdf > data.triples
rapper: Parsing URI file:///srv/ncbo/share/env/production/repository/ONTOPARON_SOCIAL/2/owlapi.xrdf with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Parsing returned 7462 triples

[ncbo-deployer@ncbo-prd-app-25 2]$ rapper -i ntriples -c data.triples
rapper: Parsing URI file:///srv/ncbo/share/env/production/repository/ONTOPARON_SOCIAL/2/data.triples with parser ntriples
rapper: Parsing returned 7462 triples
```

**Comment by jonquet** [comment]
Experienced the same error on SIFR BioPortal (http://bioportal.lirmm.fr). 

I can’t figure out why the parser stop before processing the submission. 
I have removed a couple of things from the .owl that look suspect to me: e.g., 
- special character for « absence »
- empty label for appareil
- changes the &xxx; characters to normal
- remove the * in some URIs

But stil, I can’t get rid of an issue.

**Comment by jonquet** [comment]
Find the bug today: 

 <owl:Class rdf:about="http://www.limics.fr/ontologies/ontoparonnoy#DemandeUrgente">
was defined with a label

**Comment by jvendetti** [comment]
Jean uploaded a new version of the ontology that includes a fix for the issue with the xml:lang tag. I confirmed that this new version loads/parses in BioPortal without errors.
