### ISSUE TITLE
TIME: failed to parse

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#66]
Both submissions of the [TIME ontology](http://bioportal.bioontology.org/ontologies/TIME) failed to parse in BioPortal. According to the parsing log file, the failure occurs when we generate missing labels and try to load that data into the triplestore:

```
I, [2018-02-07T11:34:38.235297 #23635]  INFO -- : ["OWLAPI Java command: parsing finished successfully."]
I, [2018-02-07T11:34:38.235458 #23635]  INFO -- : ["Output size 118088 in `/srv/ncbo/repository/TIME/2/owlapi.xrdf`"]
I, [2018-02-07T11:34:39.391623 #23635]  INFO -- : ["Triples /srv/ncbo/repository/TIME/2/owlapi.xrdf appended in <http://data.bioontology.org/ontologies/TIME/submissions/2>"]
E, [2018-02-07T11:34:39.794608 #23635] ERROR -- : ["Exception: Rapper cannot parse turtle file at /tmp/data_triple_store20180207-23635-1lftv1j: rapper: Parsing URI file:///tmp/data_triple_store20180207-23635-1lftv1j with parser turtle
rapper: Serializing with serializer ntriples
rapper: Error - URI file:///tmp/data_triple_store20180207-23635-1lftv1j:6 - syntax error at '<'
rapper: Parsing returned 5 triples

/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-999634f3a875/lib/goo/sparql/client.rb:59:in `bnodes_filter_file'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-999634f3a875/lib/goo/sparql/client.rb:80:in `append_triples_no_bnodes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-999634f3a875/lib/goo/sparql/client.rb:121:in `append_data_triples'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-999634f3a875/lib/goo/sparql/client.rb:147:in `append_triples'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-d6718646d37c/lib/ontologies_linked_data/models/ontology_submission.rb:562:in `generate_missing_labels_pre'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-d6718646d37c/lib/ontologies_linked_data/models/ontology_submission.rb:519:in `call'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-d6718646d37c/lib/ontologies_linked_data/models/ontology_submission.rb:519:in `block in loop_classes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-d6718646d37c/lib/ontologies_linked_data/models/ontology_submission.rb:478:in `block in process_callbacks'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-d6718646d37c/lib/ontologies_linked_data/models/ontology_submission.rb:474:in `delete_if'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-d6718646d37c/lib/ontologies_linked_data/models/ontology_submission.rb:474:in `process_callbacks'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-d6718646d37c/lib/ontologies_linked_data/models/ontology_submission.rb:518:in `loop_classes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/ontologies_linked_data-d6718646d37c/lib/ontologies_linked_data/models/ontology_submission.rb:930:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:177:in `process_submission'
	bin/ncbo_ontology_process:98:in `block in <main>'
	bin/ncbo_ontology_process:81:in `each'
	bin/ncbo_ontology_process:81:in `<main>'"]
```

**Comment by jvendetti** [comment]
Samson Tu (member of the Protege team) pointed out on our support list that: "The ontology includes a (xsd:dateTimeStamp rdfs:subClassOf rdfs:Literal) axiom. This mixing of datatype and class is not right." Screen shot of the ontology class tree in Protege showing rdfs:Literal:

![screenshot 2018-02-09 11 20 21](https://user-images.githubusercontent.com/1696923/36045909-0ad066d6-0d8c-11e8-9d05-dc62a8f8516f.png)

I removed that particular axiom and uploaded the modified ontology to our staging environment where it parsed without errors:

![screenshot 2018-02-09 11 17 03](https://user-images.githubusercontent.com/1696923/36045935-293bd196-0d8c-11e8-9bc9-d2bb21db1011.png)

**Comment by dr-shorthair** [comment]
That axiom is not in the published version https://www.w3.org/2006/time

**Comment by jvendetti** [comment]
Yes, I'm aware. BioPortal is configured to pull new versions from http://www.w3.org/2006/time:

![screenshot 2018-07-10 11 16 15](https://user-images.githubusercontent.com/1696923/42529207-b3e097d8-8432-11e8-81b0-3c78bf9e1642.png)

The source file that was pulled on Sept. 18, 2017 had the axiom. The newer version that was pulled on Feb. 13, 2018 doesn't have it:

![screenshot 2018-07-10 11 19 01](https://user-images.githubusercontent.com/1696923/42529335-12109484-8433-11e8-9bd1-c317f68ec5ef.png)
