### ISSUE TITLE
NEST: submission 1.2 failed to parse

### ISSUE THREAD

**Issue by mdorf** [ncbo/bioportal-project#87]
Version 1.2 of the Nutritional Epidemiological STandards (NEST) failed to parse.

Pertinent snippet from the parsing log file:

2018-08-20T03:06:16 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - Serializing ontology in RDF ...
2018-08-20T03:06:16 [main] ERROR o.s.ncbo.oapiwrapper.OntologyParser - http://one.ugent.be/00061
http://one.ugent.be/00073
http://one.ugent.be/00051
http://one.ugent.be/00068
http://one.ugent.be/00057
http://one.ugent.be/00077
http://one.ugent.be/00067
http://one.ugent.be/00023
http://one.ugent.be/00001
http://one.ugent.be/00034
http://one.ugent.be/00028
2018-08-20T03:06:16 [main] INFO  o.s.n.o.OntologyParserCommand - Parse result: false

**Comment by mdorf** [comment]
Running the ontology through the OWLAPIWrapper produces a more descriptive error:

2018-08-20T15:13:09 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - Serializing ontology in RDF ...
org.semanticweb.owlapi.model.OWLOntologyStorageException: http://one.ugent.be/00061
http://one.ugent.be/00073
http://one.ugent.be/00051
http://one.ugent.be/00068
http://one.ugent.be/00057
http://one.ugent.be/00077
http://one.ugent.be/00067
http://one.ugent.be/00023
http://one.ugent.be/00001
http://one.ugent.be/00034
http://one.ugent.be/00028
	at org.semanticweb.owlapi.rdf.rdfxml.renderer.RDFXMLStorer.storeOntology(RDFXMLStorer.java:57)
	at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
	at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1264)
	at org.stanford.ncbo.oapiwrapper.OntologyParser.serializeOntology(OntologyParser.java:616)
	at org.stanford.ncbo.oapiwrapper.OntologyParser.internalParse(OntologyParser.java:605)
	at org.stanford.ncbo.oapiwrapper.OntologyParser.parse(OntologyParser.java:576)
	at org.stanford.ncbo.oapiwrapper.OntologyParserTest.parse_OntologyNEST_ReturnsTrue(OntologyParserTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.semanticweb.owlapi.rdf.rdfxml.renderer.IllegalElementNameException: Illegal Element Name (Element Is Not A QName): http://one.ugent.be/00061
http://one.ugent.be/00073
http://one.ugent.be/00051
http://one.ugent.be/00068
http://one.ugent.be/00057
http://one.ugent.be/00077
http://one.ugent.be/00067
http://one.ugent.be/00023
http://one.ugent.be/00001
http://one.ugent.be/00034
http://one.ugent.be/00028
	... 32 more

**Comment by mdorf** [comment]
Caused by: org.semanticweb.owlapi.rdf.rdfxml.renderer.IllegalElementNameException: Illegal Element Name (Element Is Not A QName).

This error is reminiscent of #16 .

**Comment by graybeal** [comment]
I believe I learned the answer relating to both of these issues. (From Matthew, but translated through my weaker brain, so some of this may not be precisely correct.)

http://one.ugent.be/00057 is both an Annotation and a Class in the OWL file. (You can see this in Protege, if you know the little purple things are Annotations and the little orange circles are Classes.)  When an OWL file is converted to RDF/XML, it is necessary to convert the properties (which Annotations are) to QNames.  

Unfortunately, in addition to QNames not being able to include colons (#16 problem), QNames also can not start with a digit. So the resulting transformation produces an RDF/XML which can not be parsed.

If the OWL file is converted first to TTL before ingesting, TTL can represent this appropriately; it may be that this gives us a workaround. I'm testing this with TESTING_JBG but jury is still out.
